## Discretization in space

Discretization of the domain in the finite element method amounts to partitioning $\Omega$ into a union of cells $\Omega\approx\cup_{\mathcal{K}}\mathcal{K}$, which can be triangular or quadrilateral in 2D, and tetrahedral or hexahedral in 3D, to form a computational mesh. A mesh is said to be structured if its vertices form a grid, and uniform if the grid spacings are constant. We use the open-source finite element library FEniCS \cite{baratta_dolfinx_2023} for the creation of a mesh, writing of variational forms, and numerical solution of the resulting linear systems. The open-source meshing library Gmsh [cite], which interfaces with FEniCS, is used for meshing more complicated domains, since FEniCS's built-in meshing module only implements intervals (1D), rectangles (2D) and boxes (3D).

Use of the finite element method, rather than alternatices such finite volume, finite difference or spectral methods, is motivated by the abundance of existing general-purpose numerical software for solving PDEs via the finite element method, such as the FEniCS \cite{baratta_dolfinx_2023} and deal.II \cite{arndt_dealii_2021} libraries. The finite element method has a number of strengths making it a sutable candidate for creating a general-purpose solver to \eqref{eq:FiniteDifferenceHeatTransport}-\eqref{eq:FiniteDifferenceEvolution}. Whereas spectral methods, for example as implemented by the Dedalus library [cite], are less capable of handling non-constant coefficients, such as the porosity, permemability and reaction in our governing equations \eqref{eq:FiniteDifferenceHeatTransport}-\eqref{eq:FiniteDifferenceEvolution}, these do not present a difficluty in the finite element method. To model a domain having some complicated or irregular shape, the finite element method can use unstructured mesh whereas spectral or finite difference methods are typically limited to simpler domains (e.g. Cartesian or curvilinear) discretized as a structured grid. We settled on using the FEniCS library \cite{baratta_dolfinx_2023} for our numerical solutions owing to its user-friendly Python application-programming interface (API) which would furthermore facilitate postprocessing of numerical results within the well-established ecosystem of scientific Python packages, including Numpy, SciPy and Matplotlib [cite].

The finite element method requires \eqref{eq:NonDimensionalHeatTransport}-\eqref{eq:NonDimensionalEvolution} to first be written in variational form, which we discuss at length in appendix \ref{chap:FiniteElementFormulation}. Particular attention must be paid to the transport equations \eqref{eq:FiniteDifferenceHeatTransport} and \eqref{eq:FiniteDifferenceSoluteTransport}, because the numerical solution obtained by the finite element method is well-known to suffer spurious oscillations in the advection-dominated (i.e. $Rb, Ra \to\infty$) limit or in the vicinity of sharp gradients, say due to a prescribed initial condition or boundary condition. A finer mesh can improve this, but it is not computationally pheasible to use an ever-increasing mesh resolution. Stabilized finite element formulations for the advection-dominated case are included in appendix \ref{chap:FiniteElementFormulation}.  In the case of \eqref{eq:FiniteDifferenceSoluteTransport}, another cause of spurious oscillations in the numerical solution can be due to the reaction term dominating \eqref{eq:FiniteDifferenceSoluteTransport} (i.e. $Da\to\infty$ provided that $R\neq 0$), which in effect makes the differential equation `stiff' and require impractically-small timesteps to avoid numerical instability. As a somewhat blunt but nonetheless effective defence against spurious oscillations, we follow [cite] and also include in our numerical simulation program the option to correct at each step in the numerical integration any values of the temperature and concentration that fall outside the physically-permitted ranges. In the simple case of the finite element approximation $\theta^{n}(\textbf{x})=\sum_j\theta^{n}_j\xi_j(\textbf{x})$ having for its degrees-of-freedom $\{\theta^n_j\}_j$ pointwise evaluations (as opposed to more exotic evaluations such as integral moments or derivatives), then a simple correction algorithm restricting $\theta^n\in[\theta_{\text{min}},\theta_{\text{max}}]$ can be implemented by $\theta_j^n\gets\theta_{\text{max}}$ if $\theta_j^n>1$ and $\theta_j^n\gets\theta_{\text{min}}$ if $\theta_j^n<\theta_{\text{min}}$.

We use continuous linear Lagrange elements $\text{P}_1$ for the temperature $\theta$ and concentration $c$, unless the variational formulation chosen is discontinuous Galerkin (DG) in which case discontinuous linear Lagrange elements $\text{DP}_1$ are instead used. $\text{P}_1$ elements are also used for the saturation $s$. Solving \eqref{eq:FiniteDifferenceContinuity} and \eqref{eq:FiniteDifferenceDarcy} requires a mixed finite element method solving for $(\textbf{u}, p)$ together. The choice of finite elements in mixed problems must satisfy the inf-sup condition [cite], and we use $\text{BDM}_1$-$\text{DP}_0$ pair which is well-known to be stable for solving the Darcy flow equations [cite]. In the streamfunction formulation, we use continuous quadratic Lagrange elements $\text{P}_2$ for the streamfunction $\psi$ which is then differentiated to obtain the velocity components \eqref{eq:FiniteDifferenceStreamfunctionVelocity}, for which we use $\text{DP}_1$ elements.
 -->
