project:
  type: book
  render:
    - index.qmd
    - asbtract.qmd
    - acknowledgemenåts.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - references.qmd

book:
  title: "Modelling of Advective-Diffusive-Reactive Flows in Geological Carbon Sequestration"
  author: "George Poole"
  chapters:
    - index.qmd
    - asbtract.qmd
    - acknowledgements.qmd
    - toc.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    include-in-header: mathjax.html
    theme:
      - cosmo
      - brand
    toc: true
    toc-depth: 3
    number-depth: 3
  pdf:
    documentclass: scrreprt
    number-depth: 3
    toc: false  


